### ISSUE TITLE
Include AWS SDK migration-tool once releases

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-third-party#9]
## What problem are you trying to solve?
AWS is working on a migration tool for SDK users, in a feature branch:
https://github.com/aws/aws-sdk-java-v2/tree/feature/master/migration-tool/migration-tool

## Describe the solution you'd like
Once the above tool is released, it would be nice to add the recipe jar here, such that users can more easily find and run these recipes.

**Comment by okundzich** [comment]
curious, are they working on recipes or a wrapper over recipes like spring boot migrator/advisor?

**Comment by timtebeek** [comment]
Looks to be just recipes; their usage instructions say to use the OpenRewrite Maven plugin to run their recipes.

**Comment by timtebeek** [comment]
Draft available here
- https://github.com/openrewrite/rewrite-third-party/pull/15

One thing I'd wondered is if we should include any notice on third party dependencies being included here, and their licenses. It's fairly obvious with this being called `rewrite-third-party` that those are external, but could still be good to have some clarity on.
